apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: load-demo-ui
  namespace: load-demo
spec:
  minReplicas: 3
  minReplicas: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: load-demo-ui
